import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/component/layout/NavBar";
import Footer from "@/component/layout/Footer";
import { Inter } from "next/font/google";
import AOSInit from "@/lib/AOSInit";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-[#0B1220] text-[#E5E7EB]`}
      >
        <AOSInit />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
